[2025-10-06T19:17:03.919+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T19:17:03.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-06T19:13:59.733497+00:00 [queued]>
[2025-10-06T19:17:03.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-06T19:13:59.733497+00:00 [queued]>
[2025-10-06T19:17:03.937+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-10-06T19:17:03.944+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-06 19:13:59.733497+00:00
[2025-10-06T19:17:03.950+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-06T19:17:03.951+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2025-10-06T19:17:03.951+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'manual__2025-10-06T19:13:59.733497+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp2b3y6axj']
[2025-10-06T19:17:03.960+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask load_model_task
[2025-10-06T19:17:03.988+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-06T19:13:59.733497+00:00 [running]> on host 5a007d4eb749
[2025-10-06T19:17:04.041+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T19:13:59.733497+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T19:13:59.733497+00:00'
[2025-10-06T19:17:04.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T19:17:04.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T19:17:04.053+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_model_predict() takes 1 positional argument but 2 were given
[2025-10-06T19:17:04.058+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1, task_id=load_model_task, run_id=manual__2025-10-06T19:13:59.733497+00:00, execution_date=20251006T191359, start_date=20251006T191703, end_date=20251006T191704
[2025-10-06T19:17:04.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task load_model_task (load_model_predict() takes 1 positional argument but 2 were given; 218)
[2025-10-06T19:17:04.092+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-06T19:17:04.102+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T19:17:04.102+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
